# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    desc: Run the full "Confidence Suite" before a push
    cmds:
      - task: format
      - task: type-check
      - task: tests
    silent: false

  format:
    desc: Fix linting and format code with Ruff
    cmds:
      - uv run ruff check --fix
      - uv run ruff format
    silent: true

  type-check:
    desc: Deep semantic analysis using Pyre (The Senior Move)
    cmds:
      - echo "Running Pyre incremental check..."
      - uv run pyrefly check --summarize-errors
    silent: false

  tests:
    desc: Run all tests (including benchmarks)
    cmds:
      - uv run pytest
    silent: true

  check-all:
    desc: Extreme strictness check (Ruff + Pyre + Lockfile)
    cmds:
      - uv lock --check
      - task: format
      - task: type-check
      - task: tests
    silent: false